name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate gcloud
      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      # Set up gcloud CLI
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cse-2024-g5-api

      - name: Building
        run: |-
          gcloud builds submit \
            --tag gcr.io/cse-2024-g5-api/cse-2024-g5-api

      # Deploy to Cloud Run
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cse-2024-g5-api
          image: gcr.io/cse-2024-g5-api/cse-2024-g5-api
          region: europe-north1
          project_id: cse-2024-g5-api
